# Suppress all Hibernate internal logging
org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.org.hibernate=warn
org.slf4j.simpleLogger.log.com.zaxxer=warn
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
